name: Deploy to Minikube
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-web-app .
      - name: Run Minikube
        run: minikube start
      - name: Deploy to Minikube
        run: kubectl apply -f deployment.yaml

